app/exchangeapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add_product/', views.ProductAddView.as_view(), name='add-product'),
    path('all_products/', views.ProductsDisplayAllView.as_view(), name='display-all-products'),
    path('<str:username>/products/', views.UserProductsView.as_view(), name='user-products-list'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name="product-detail"),
]

app/stuff_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('exchangeapp.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/exchangeapp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.text import slugify



class ProductCategory(models.Model):
    title = models.CharField(verbose_name='Название', max_length=50, db_index=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title


class Product(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Владелец',
        related_name='products',
        on_delete=models.CASCADE,
        default="",
    )
    title = models.CharField(verbose_name='Название', max_length=50, db_index=True)
    slug = models.SlugField(verbose_name='Product slug', max_length=100, unique=True)
    description = models.TextField(verbose_name='Описание', max_length=500)
    exchange_offer = models.CharField(verbose_name='Что хочу взамен', max_length=50, db_index=True)
    category = models.ForeignKey(
        ProductCategory,
        verbose_name='Категория',
        related_name='products',
        null=True,
        on_delete=models.SET_NULL,
    )
    created_at = models.DateTimeField('Дата регистрации', default=timezone.now, db_index=True)
    published = models.BooleanField('Опубликован', default=True, db_index=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.title} {get_random_string(5)}')
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.slug)])


class ProductImage(models.Model):
    position = models.PositiveIntegerField(default=0, db_index=True)
    image = models.ImageField(upload_to='images')
    product = models.ForeignKey(
        Product,
        related_name='images',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['position']
        verbose_name = 'изображение'
        verbose_name_plural = 'изображения'

    def __str__(self):
        return f'{self.position} {self.product.title}'

    @property
    def get_absolute_image_url(self):
        """Get the full path to the image."""
        return f'{self.image.url}'

app/exchangeapp/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row
from django import forms

from .models import Product, ProductImage


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'category', 'description', 'exchange_offer')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Например, IPhone 13'}),
            'exchange_offer': forms.TextInput(attrs={'placeholder': 'Например, IPhone 13'}),
            'description': forms.Textarea(attrs={'placeholder': 'Расскажите об особенностях своего товара'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.form_tag = False
            self.helper.disable_csrf = True
            self.helper.layout = Layout(
                'title',
                'description',
            )


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ('image', )
        widgets = {
            'image': forms.ClearableFileInput(
                attrs={'multiple': False},
            ),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.form_tag = False
            self.helper.disable_csrf = True
            self.helper.layout = Layout(
                Row(
                    'image', css_class="form-group col-md-10 mb-0",
                )
            )


ProductImageFormSet = forms.models.inlineformset_factory(
    parent_model=Product,
    model=ProductImage,
    form=ProductImageForm,
    can_delete=False,
    error_messages={'image': {'Обязательное поле': 'Пожалуйста, предоставьте изображение.'}},
    extra=4,
    min_num=1,
    max_num=5,
    validate_min=True,
    validate_max=True,
)

app/user_profile/forms.py
from django import forms

from allauth.account.forms import SignupForm


class StuffExchangeSignupForm(SignupForm):
    phonenumber = forms.CharField()
    vk_link = forms.CharField(required=False)
    telegram_link = forms.CharField(required=False)
    city = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def custom_signup(self, request, user):
        user.vk_link = self.cleaned_data['vk_link']
        user.telegram_link = self.cleaned_data['telegram_link']
        user.city = self.cleaned_data['city']
        user.phonenumber = self.cleaned_data['phonenumber']
        user.save()

app/exchangeapp/views.py
from django.views.generic import CreateView, DetailView, ListView

from .forms import ProductForm, ProductImageFormSet
from .models import Product

ITEMS_PER_PAGE = 9


class ProductAddView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/add_product.html'

    def get_context_data(self, **kwargs):
        context = super(ProductAddView, self).get_context_data(**kwargs)
        context['user_username'] = self.request.user.username
        if self.request.POST:
            context['images'] = ProductImageFormSet(self.request.POST, self.request.FILES)
        else:
            context['images'] = ProductImageFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        images = context['images']

        product_instance = form.save(commit=False)
        product_instance.owner = self.request.user
        product_instance.save()

        if images.is_valid():
            product_instance = form.save()
            images.instance = product_instance
            images.save()

        else:
            return self.form_invalid(form)
        return super(ProductAddView, self).form_valid(form)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_details.html'

    def get_context_data(self, **kwargs):
        context = {
            'user_username': self.request.user.username,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class ProductsDisplayAllView(ListView):
    model = Product
    template_name = 'product/all_products.html'
    paginate_by = ITEMS_PER_PAGE

    def get_context_data(self, **kwargs):
        user_products = self.get_queryset()
        context = {
            'products_amount': user_products.count(),
            'user_username': self.request.user.username,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserProductsView(ListView):
    model = Product
    template_name = 'product/user_products.html'
    paginate_by = ITEMS_PER_PAGE

    def get_context_data(self, **kwargs):
        user_products = self.get_queryset()
        context = {
            'products_amount': user_products.count(),
            'owner_username': self.kwargs['username'],
            'user_username': self.request.user.username,

        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return super(UserProductsView, self).get_queryset().filter(owner__username=self.kwargs['username'])

app/exchangeapp/templates/inlines/base.html
{% load static %}
<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <!-- Bootstrap icons-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <title>Stuff Exchange</title>
</head>

<body>
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <div class="logo_container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            <img src="{% static 'img/site-icon.jpg' %}" width="30" height="30" alt="Website icon" />
          </a>
        </div>
      </div>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" target="_blank" class="nav-link px-2">Хочу обменять</a></li>
        <li><a href="#" target="_blank" class="nav-link px-2">Хотят обменять</a></li>
        <li><a href="#" target="_blank" class="nav-link px-2">Предложения обмена</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'account_logout' %}" target="_blank" class="nav-link px-2">Выход</a></li>
        {% else %}
          <li><a href="{% url 'account_login' %}" target="_blank" class="nav-link px-2">Вход</a></li>
          <li><a href="{% url 'account_signup' %}" target="_blank" class="nav-link px-2">Регистрация</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="container">
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </div>
  <!-- Footer -->
  <footer class="footer mt-auto py-3 bg-secondary">
    <div class="container">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2">О проекте</a></li>
        <li><a href="#" class="nav-link px-2">Написать нам</a></li>
        <li><a href="#" class="nav-link px-2">Мобильная версия</a></li>
        <li><a href="#" class="nav-link px-2">Правила размещения объявлений</a></li>
      </ul>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>

</html>

app/exchangeapp/templates/inlines/footer.html
<footer class="footer footer-big footer-black">
  <div class="container">
    <div class="social-area text-center">
      <h5>Мы в соцсетях</h5>
      <a href="#" class="btn btn-social btn-round">
        <i class="fa fa-facebook"></i>
      </a>
      <a href="#" class="btn btn-social btn-round">
        <i class="fa fa-twitter"></i>
      </a>
    </div>
    <div class="copyright">
      &copy; 2021
    </div>
  </div>
</footer>

app/exchangeapp/templates/inlines/head.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Stuff exchange</title>
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'img/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/gsdk.css' %}" rel="stylesheet" />
  <link href="{% static 'css/examples.css' %}" rel="stylesheet" />
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
</head>

app/exchangeapp/templates/inlines/modal.html
<div class="modal modal-small fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-center">Вход</h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'account_login' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.get_full_path }}"/>
          <div class="form-group">
            <input id="id_login" name="login" type="text" value="" placeholder="Имя пользователя" class="form-control"/>
          </div>
          <div class="form-group">
            <input id="id_password" name="password" type="password" value="" placeholder="Password"
                   class="form-control"/>
          </div>
          <label class="checkbox" for="id_remember">
            <input type="checkbox" value="" id="id_remember" data-toggle="checkbox">
            Запомнить
          </label>
          <button type="submit" class="btn btn-info btn-fill btn-block"> Login</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal Register-->
<div class="modal modal-small fade" id="registerModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-center">Регистрация</h4>
      </div>
      <div class="modal-body">
        <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_username">Имя пользователя</label>
            <input type="text" name="username" class="form-control" id="name" placeholder="Имя пользователя"
                   autocomplete="username" minlength="1" maxlength="50" required id="id_username"/>
          </div>
          <div class="form-group">
            <label for="phone">Phone</label>
            <input type="text" name="phonenumber" class="form-control" id="phone" required id="id_phonenumber"
                   placeholder="Phone number"/>
          </div>
          <div class="form-group">
            <label for="id_email">Email (опционально)</label>
            <input type="email" name="email" class="form-control" id="email"
                   placeholder="Ваш персональный email адрес" autocomplete="email" id="id_email"/>
          </div>
          <div class="form-group">
            <label for="id_city">Город (опционально)</label>
            <input type="text" name="city" class="form-control" placeholder="Москва">
          </div>
          <div class="form-group">
            <label for="id_vk_link">Ссылка на аккаунт ВК (опционально)</label>
            <input type="text" name="vk_link" class="form-control" placeholder="https://vk.com/durov">
          </div>
          <div class="form-group">
            <label for="id_telegram_link">Ссылка на аккаунт Telegram (опционально)</label>
            <input type="text" name="telegram_link" class="form-control" placeholder="http://t.me/durov">
          </div>
          <div class="form-group">
            <label for="id_password1">Пароль:</label>
            <input type="password" name="password1" placeholder="Пароль" autocomplete="new-password" required
                   id="id_password1" class="form-control">
          </div>
          <div class="form-group">
            <label for="id_password2">Пароль (еще раз):</label>
            <input type="password" name="password2" placeholder="Пароль (еще раз)" required id="id_password2"
                   class="form-control">
          </div>
          <button type="submit" class="btn btn-info btn-fill btn-block"> Создать аккаунт</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!--    end modal -->

app/exchangeapp/templates/inlines/navbar.html
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button id="menu-toggle" type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar bar1"></span>
        <span class="icon-bar bar2"></span>
        <span class="icon-bar bar3"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="{% url 'add-product' %}">
            Хочу обменять
          </a>
        </li>
        <li>
          <a href="{% url 'display-all-products' %}">
            Хотят обменять
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="btn btn-round btn-default" data-toggle="dropdown">
            {{ user_username }}
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu dropdown-with-icons">
            <li>
              <a href="{% url 'account_logout' %}">
                <i></i> Выход
              </a>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="dropdown">
          <a href="#" class="btn btn-round btn-default" data-toggle="dropdown">
            Гость
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu dropdown-with-icons">
            <li>
              <a href="" data-toggle="modal" data-target="#loginModal">
                <i></i> Вход
              </a>
            </li>
            <li>
              <a href="" data-toggle="modal" data-target="#registerModal">
                <i></i> Регистрация
              </a>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

app/exchangeapp/templates/inlines/pagination.html
{% if is_paginated %}
  <div class="text-center">
    <nav aria-label="page_navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li><a href="?page=1">&laquo;&laquo;</a></li>
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
          {% if page_obj.number == page %}
            <li class="active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endif %}
        {% endfor %}
          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;&raquo;</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endif %}

app/exchangeapp/templates/inlines/scripts.html
{% load static %}

<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.custom.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/gsdk-checkbox.js' %}"></script>
<script src="{% static 'js/gsdk-morphing.js' %}"></script>
<script src="{% static 'js/gsdk-radio.js' %}"></script>
<script src="{% static 'js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/chartist.min.js' %}"></script>
<script src="{% static 'js/jquery.tagsinput.js' %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
<script src="{% static 'js/get-shit-done.js' %}"></script>
<script type="text/javascript">

var big_image;
var transparent = true;

$().ready(function() {
  responsive = $(window).width();

  $(window).on('scroll', checkScroll);

  if (responsive >= 768) {
    big_image = $('.parallax-image').find('img');

    $(window).on('scroll', function() {
      parallax();
      checkScroll();
    });
  }

});

function checkScroll() {
  if ($(document).scrollTop() > 260) {
    if (transparent) {
      transparent = false;
      $('nav[role="navigation"]').removeClass('navbar-transparent').addClass('navbar-default');
    }
  } else {
    if (!transparent) {
      transparent = true;
      $('nav[role="navigation"]').addClass('navbar-transparent').removeClass('navbar-default');
    }
  }
}

var parallax = function() {
  var current_scroll = $(this).scrollTop();

  oVal = ($(window).scrollTop() / 3);
  big_image.css('top', oVal);
};

</script>